/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OrionChatClientServerEvents = UserMessageEvent | PermissionDecisionEvent | AbortEvent | AskUserAnswerEvent;
export type Type = "user_message";
export type Content = string;
export type Type1 = "permission_decision";
export type RequestId = string;
export type Decision = "allow" | "always_allow" | "deny";
export type Type2 = "abort";
export type Type3 = "ask_user_answer";
export type RequestId1 = string;

export interface UserMessageEvent {
  type?: Type;
  content: Content;
  [k: string]: unknown;
}
export interface PermissionDecisionEvent {
  type?: Type1;
  request_id: RequestId;
  decision: Decision;
  [k: string]: unknown;
}
export interface AbortEvent {
  type?: Type2;
  [k: string]: unknown;
}
/**
 * client 回覆 server 的 AskUserQuestionAskEvent。
 *
 * `answers` 是 question text → 使用者選的 label(或開放式回答的純文字)。
 * 若使用者放棄/超時,client 可送 `answers={}` 提早通知。
 */
export interface AskUserAnswerEvent {
  type?: Type3;
  request_id: RequestId1;
  answers: Answers;
  [k: string]: unknown;
}
export interface Answers {
  [k: string]: string;
}
